name: Configure Repository

on:
  workflow_call:

env:
  DF_ORG: 'dynamic-framework'
  DF_ADMINS: 'dynamic-framework-admins'
  DF_TEAM: 'dynamic-framework-team'

jobs:
  configure:
    name: 'Configure project with initial rules'
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install jsonwebtoken
        run: npm install jsonwebtoken

      - name: Generate token
        uses: actions/github-script@v7
        id: generate-token
        with:
          script: |
            const jwt = require('jsonwebtoken');
            const now = Math.floor(Date.now() / 1000);
            const payload = {
              iat: now, 
              exp: now + 200,
              iss: process.env.APP_ID, 
            };

            const privateKey = process.env.APP_PRIVATE_KEY.replace(/\\n/g, '\n');
            const token = jwt.sign(payload, privateKey, { algorithm: 'RS256' });
            console.log('Set token');
            core.setOutput('token', token);
        env:
          APP_ID: ${{ vars.APP_ID }}
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Check token 2
        run: |
          curl --request GET \
          --url "https://api.github.com/app/installations" \
          --header "Accept: application/vnd.github+json" \
          --header "Authorization: Bearer ${{ steps.generate-token.outputs.token }}" \
          --header "X-GitHub-Api-Version: 2022-11-28"

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up teams
        run: |
          gh api \
          -X PUT \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /orgs/${{ env.DF_ORG }}/teams/${{ env.DF_TEAM }}/repos/${{ github.repository }} \
          -f "permission=push"

          gh api \
          -X PUT \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /orgs/${{ env.DF_ORG }}/teams/${{ env.DF_ADMINS }}/repos/${{ github.repository }} \
          -f "permission=admin"
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}